try { //ครอบตรงที่คาบว่าจโปรแกรมจะล่มหรือมีปัญหา
    let i = 10;
    console.log(i / 0);
} catch (e) { //จะทำงานเมื่อโปรแกรมล่มเรียบร้อยหรือมีปัญหา
    //e คือตัวแปลของ error
    console.log(e);
}